### ISSUE TITLE
Missing NuGet and PSGallary Required for Registration

### ISSUE THREAD

**Issue by DellProSupportGse** [MicrosoftDocs/azure-stack-docs#2076] opened 2022-11-09 18:01 UTC
Please add NuGet and PSGallary to this list as it is required to be able to install the registration module as stated this Doc [https://learn.microsoft.com/en-us/azure-stack/hci/deploy/register-with-azure#register-a-cluster-using-powershell](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2957e994-0bc8-aeb6-0c54-f7d2a8ec9fe3
* Version Independent ID: ee2cad3d-41ce-bf5a-dd17-0886e526570e
* Content: [Install and use behind a firewall or proxy server - Visual Studio (Windows)](https://learn.microsoft.com/en-us/visualstudio/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server?view=vs-2022)
* Content Source: [docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md](https://github.com/MicrosoftDocs/visualstudio-docs/blob/main/docs/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server.md)
* Product: **visual-studio-windows**
* Technology: **vs-installation**
* GitHub Login: @anandmeg
* Microsoft Alias: **meghaanand**

**Comment by DellProSupportGse** [comment] 2022-11-09 18:56
When you register an Azure Stack HCI cluster you have to run Install-Module -Name Az.StackHCI which goes to NuGet to get the required modules for the registration. If we are not able to download the modules, we will not be able to register the HCI cluster with Azure. 

The link I provided shows a note that NuGet and PSGallary are required.  

 Note

You may see a prompt such as Do you want PowerShellGet to install and import the NuGet provider now? Answer Yes(Y).

If you see another prompt saying Are you sure you want to install the modules from 'PSGallery'? Answer Yes(Y).

**Comment by DellProSupportGse** [comment] 2022-11-09 18:58
Add NuGet and PSGallery to the Required firewall URLs table

**Comment by DellProSupportGse** [comment] 2022-11-09 19:02
You can find the NuGet URLs and ports documented in the Visual Studio and Azure Services behind a firewall or proxy server
[https://learn.microsoft.com/en-us/visualstudio/install/install-and-use-visual-studio-behind-a-firewall-or-proxy-server?view=vs-2022](url)

**Comment by DellProSupportGse** [comment] 2022-11-10 20:35
No I am not asking for the Visual Studio article to be updated. I am asking for the missing NuGet URL's to be added to the Firewall requirements for Azure Stack HCI article ([https://learn.microsoft.com/en-us/azure-stack/hci/concepts/firewall-requirements](url). The Visual Studio article has the NuGet URLs listed that need to be also added to the Firewall requirements for Azure Stack HCI.

**Comment by sethmanheim** [comment] 2022-11-10 20:58
Got some clarification -- #please-open

**Comment by SaibabaBalapur-MSFT** [comment] 2022-11-11 04:17
@DellProSupportGse 
Thanks for bringing this to our attention.
I'm going to assign this to the document author so they can take a look at it accordingly.

**Comment by anandmeg** [comment] 2022-11-11 05:06
#assign: @cosmosdarwin

**Comment by anandmeg** [comment] 2022-11-11 05:08
#assign: @SaibabaBalapur-MSFT 
The issue is on https://learn.microsoft.com/en-us/azure-stack/hci/concepts/firewall-requirements, I'm not the author of this doc. Please reassign. Thanks!

**Comment by SaibabaBalapur-MSFT** [comment] 2022-11-11 07:24
@alexbuckgit
Could you please look into this.

**Comment by sethmanheim** [comment] 2022-11-11 16:10
This issue tags the incorrect article. We are addressing the issue and it's being worked on in a PR in the private repo. #please-close

**Closed by sethmanheim** 2022-11-11 16:10 UTC
Labels: assigned-to-author, product-question, triaged, Pri3, visual-studio-windows/prod, vs-installation/tech
