### ISSUE TITLE
Syspreping a Azure Stack HCI VHDx

### ISSUE THREAD

**Issue by aricbernard** [MicrosoftDocs/azure-stack-docs#1916] opened 2022-03-31 00:49 UTC
The content states "You can prepare the VHD using Sysprep".  After syspreping a VHDX containing Azure Stack HCI we receive the following (see screen shot).
![image](https://user-images.githubusercontent.com/15333804/160954264-b0ea1de6-6238-42b4-9355-b9924e8c9c86.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eeb152f-1c40-2222-c2d4-199371710080
* Version Independent ID: 09741470-9f27-a683-d042-12b22f3e4105
* Content: [System requirements for Azure Stack HCI - Azure Stack HCI](https://docs.microsoft.com/en-us/azure-stack/hci/concepts/system-requirements)
* Content Source: [azure-stack/hci/concepts/system-requirements.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/main/azure-stack/hci/concepts/system-requirements.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hci**
* GitHub Login: @JasonGerend
* Microsoft Alias: **jgerend**

**Comment by SreejaBhattacharya-MSFT** [comment] 2022-03-31 06:31
Hi @aricbernard , thanks for reaching out. We will investigate this and update you.

**Comment by ManikaDhiman** [comment] 2022-04-13 01:41
This issue is the duplicate of issue #1523, which is already resolved. Thanks!
#please-close

**Closed** 2022-04-13 06:50 UTC
Labels: azure-stack/svc, cxp, product-question, triaged, Pri2, azure-stack-hci/subsvc
