### ISSUE TITLE
SYSLOG missing

### ISSUE THREAD

**Issue by jbpaux** [MicrosoftDocs/azure-stack-docs#705] opened 2020-03-23 15:23 UTC
Hello,

SYSLOG outbound endpoint is missing. We should add :
SYSLOG (IP of SYSLOG server provided for deployment) TCP 6514 or UDP 514 Public VIP - /27
(or if we can have the true IP instead of the full /27...)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34d02f93-1ae9-eb2d-9c0f-0af012653885
* Version Independent ID: 18f15ad2-ef9b-f883-c49b-09289a2e6fb8
* Content: [Publish Azure Stack Hub services in your datacenter - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-endpoints?view=azs-2002#feedback)
* Content Source: [azure-stack/operator/azure-stack-integrate-endpoints.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-integrate-endpoints.md)
* Service: **azure-stack**
* GitHub Login: @IngridAtMicrosoft
* Microsoft Alias: **inhenkel**

**Comment by TravisCragg-MSFT** [comment] 2020-03-24 00:37
@jbpaux Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

**Comment by IngridAtMicrosoft** [comment] 2020-03-24 22:06
In review

**Comment by IngridAtMicrosoft** [comment] 2020-03-31 20:27
This is a duplicate of #706. 

#please-close

**Closed by IngridAtMicrosoft** 2020-03-31 20:27 UTC
Labels: Pri1, assigned-to-author, azure-stack/svc, doc-enhancement, triaged
