### ISSUE TITLE
For v0.60.1 release changes

### ISSUE THREAD

**Issue by walterov** [MicrosoftDocs/azure-stack-docs#1329] opened 2021-03-01 22:34 UTC
In general, through out the doc, change any explicit reference to AKS Engine like "v0.55.4" to "v0.xx.x" and tell the customer to look at the release notes for the latest AKS engine version.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 374a2d3f-fc08-7479-678e-cc1b28fa09c3
* Version Independent ID: 56139164-d119-c4e5-de98-3bf7cb0702bc
* Content: [Deploy the AKS engine on Windows in Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-windows?view=azs-2008)
* Content Source: [azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-windows.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/user/azure-stack-kubernetes-aks-engine-deploy-windows.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by GitaraniSharma-MSFT** [comment] 2021-03-02 11:11
@walterov , thank you for the feedback. This is a duplicate of #1328 , hence we are closing this.

**Closed by GitaraniSharma-MSFT** 2021-03-02 11:11 UTC
Labels: Pri1, azure-stack-hub/subsvc, azure-stack/svc, cxp, doc-enhancement, duplicate, triaged
