### ISSUE TITLE
Configuration Rollback

### ISSUE THREAD

**Issue by mahoncj** [MicrosoftDocs/azure-stack-docs#76] opened 2019-05-08 16:57 UTC
The command provided to rollback ADFS integration is "Reset-DatacenterIntegrationConfiguration" but in the Privileged Endpoint it is actually misspelled. The PEP has it listed as "Reset-DatacenterIntegationConfiguration".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d295c322-0813-e159-e6f8-86f04b759c48
* Version Independent ID: 02b87d3f-125b-d674-b750-79dbaee5e497
* Content: [Azure Stack datacenter integration - Identity](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-integrate-identity#feedback)
* Content Source: [azure-stack/operator/azure-stack-integrate-identity.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-integrate-identity.md)
* Service: **azure-stack**
* GitHub Login: @PatAltimore
* Microsoft Alias: **patricka**

**Comment by TravisCragg-MSFT** [comment] 2019-05-08 18:05
@mahoncj Thanks for the feedback! I have assigned the issue to the content author to evaluate and update as appropriate.

I was able to reproduce this on a 1902 ASDK.

**Comment by PatAltimore** [comment] 2019-05-09 17:51
@mahoncj and @TravisCragg-MSFT, It looks like this was fixed in https://github.com/MicrosoftDocs/azure-stack-docs/commit/4a073bafa1d9e7f27f6f23d8669aa80f258a0c54.  Am I looking at the right article? azure-stack/operator/azure-stack-integrate-identity.md?

Thanks,
Pat

**Comment by PatAltimore** [comment] 2019-05-09 17:55
#in-process

**Comment by mahoncj** [comment] 2019-05-09 18:20
Hi Pat, you are correct. The documentation was corrected, but the commandlet is still misspelled on the PEP. Hence, the doc is still wrong. :D

**Comment by PatAltimore** [comment] 2019-05-09 19:52
@mahoncj Ok. I see.  I'll change it back and let the dev team know about the misspelling in the cmdlet.

Thanks,
Pat

#please-close

**Comment by PatAltimore** [comment] 2019-05-10 19:44
@mahoncj, I checked with the dev team. It was fixed in 1904. I'm going to leave the doc with the correct spelling.

Pat

#please-close

**Comment by TravisCragg-MSFT** [comment] 2019-05-10 19:58
@mahoncj We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Closed by TravisCragg-MSFT** 2019-05-10 19:58 UTC
Labels: assigned-to-author, azure-stack/svc, doc-bug, triaged
