### ISSUE TITLE
Unable to enable Azure via Windows Admin Center

### ISSUE THREAD

**Issue by lckho3693** [MicrosoftDocs/azure-stack-docs#2039] opened 2022-10-09 07:24 UTC
Unable to enable Azure Backup via Windows Admin Center

Error:

3:18:25 PM
Source
Go to Azure Backup.
Type
Error

Message
Microsoft Azure Backup encountered an internal error. Wait for a few minutes and then try the operation again. If the issue persists, please contact Microsoft support.

**Comment by ManoharLakkoju-MSFT** [comment] 2022-10-09 14:59
@lckho3693 
Thanks for your feedback! We will investigate and update as appropriate.

**Comment by ManoharLakkoju-MSFT** [comment] 2022-10-09 15:00
@lckho3693 
Duplicate of #2038

We are going to close this thread as Duplicate.

**Closed by ManoharLakkoju-MSFT** 2022-10-09 15:00 UTC
Labels: cxp, doc-enhancement, triaged, Pri3
