### ISSUE TITLE
we need sync SQL Credentials between SQL HA servers post deployment. 

### ISSUE THREAD

**Issue by fengatms** [MicrosoftDocs/azure-stack-docs#713] opened 2020-03-25 10:19 UTC
Post app serivce 1.8 deployment with SQL HA, beside adding AppService databases (appservice_hosting and appservice_metering) to an Availability group. I also have to sync app service SQL credentials from primary instact to secondary instance. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10752bf4-4bf7-7b94-c16f-d456e32aeb51
* Version Independent ID: a23c6033-3d5c-7c4e-e0e0-e30b4629901e
* Content: [App Service on Azure Stack Hub update 8 release notes - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-release-notes-update-eight?view=azs-2002)
* Content Source: [azure-stack/operator/azure-stack-app-service-release-notes-update-eight.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-release-notes-update-eight.md)
* Service: **azure-stack**
* GitHub Login: @apwestgarth
* Microsoft Alias: **anwestg**

**Comment by BharathNimmala-MSFT** [comment] 2020-03-26 00:09
@fengatms  Thank you for your query , our team will further look into it and get back to you at the earliest.

**Comment by apwestgarth** [comment] 2020-03-26 00:14
Hi @fengatms thanks for commenting.  However that is incorrect.  The App Service databases are configured as contained databases meaning the security logins are stored in the database itself.  In 1.8 we have a regression for newly deployed databases and you need to enable contained database, and then convert the databases to partially contained.  This is covered in the release notes in known issues (post-installation).  

App Service creates new users for each worker that is added by a scale out of the underlying worker tiers, therefore if you would continually have to sync the logins which is one of the reasons we switched to contained databases.  It was a design change for other reasons too, such as supporting SQL Always On.

**Comment by TravisCragg-MSFT** [comment] 2020-03-31 16:22
@fengatms We will now proceed to close this thread. If there are further questions regarding this matter, please tag me in your reply. We will gladly continue the discussion and we will reopen the issue.

**Closed by TravisCragg-MSFT** 2020-03-31 16:22 UTC
Labels: Pri2, azure-stack/svc, cxp, product-question, triaged
