### ISSUE TITLE
Download links and installer not working

### ISSUE THREAD

**Issue by itporter** [MicrosoftDocs/azure-stack-docs#1470] opened 2021-05-25 04:18 UTC
Multiple links on the page result in a 404 message. This has been tested from multiple locations by multiple users.

- App Service App Service on Azure Stack Hub deployment helper scripts.
- App Service on Azure Stack Hub installer.

When running the Installer from a previously downloaded version, the license agreement does not load. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c085e86-242e-ac36-a611-3d379d3dcfb0
* Version Independent ID: 4d455fad-dc6a-ed4f-75c0-f8a6118aa07a
* Content: [Prerequisites to deploy Azure App Service on Azure Stack Hub - Azure Stack Hub](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-before-you-get-started?view=azs-2102&pivots=state-disconnected)
* Content Source: [azure-stack/operator/azure-stack-app-service-before-you-get-started.md](https://github.com/MicrosoftDocs/azure-stack-docs/blob/master/azure-stack/operator/azure-stack-app-service-before-you-get-started.md)
* Service: **azure-stack**
* Sub-service: **azure-stack-hub**
* GitHub Login: @BryanLa
* Microsoft Alias: **anwestg**

**Comment by psmanhas** [comment] 2021-05-25 04:59
@itporter  Thanks for the feedback! I have assigned the issue to content author to check and update the document as appropriate. We will update you accordingly.

**Comment by psmanhas** [comment] 2021-05-25 04:59
@BryanLa Can you please check and add your comments on this doc update request as applicable

**Comment by BryanLa** [comment] 2021-05-25 16:18
@itporter @psmanhas - this is a known issue and a result of something happening on download site (not the doc). Short of removing the links from the doc, there is nothing else I can do at this point. I'll advise as soon as I hear from engineering on whether the links have been restored/changed.

**Comment by BryanLa** [comment] 2021-05-25 16:30
Update... @apwestgarth has added a note to this article that will indicate the downloads are temporarily unavailable. This will publish around 10am pacific today, and be removed once the problem is resolved.

**Comment by BryanLa** [comment] 2021-06-10 18:16
Helper script for the 2020.Q2 update has been restored (https://aka.ms/appsvcupdateq2installer).

Helper script for the installer (https://aka.ms/appsvconmasinstaller) and 2020.Q3 update (https://aka.ms/appsvcupdateq3installer) are in process.

cc:@apwestgarth

**Comment by apwestgarth** [comment] 2021-06-10 23:25
Downloads for Q3 have just been re-published, I'm working on final validation and will submit a PR later tonight/first thing tomorrow morning to update docs to reinstate the links.

**Comment by BryanLa** [comment] 2021-06-10 23:53
@apwestgarth - not sure if this is on your list, but I noticed one more link.. 

For the [update](https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-app-service-update) article, we point to the 2020.Q3 download (https://aka.ms/appsvcupdateq3installer) for connected stamps. For disconnected stamps, we point to the https://aka.ms/appsvcupdate8installer download, which was also removed from DLC.

**Comment by apwestgarth** [comment] 2021-06-11 05:17
Downloads for Q3 reinstated.  Have submitted PR to reinstate them in the documentation and also have updated the update disconnected documentation.

**Comment by BryanLa** [comment] 2021-06-11 15:43
Fixed in PR 7604
#please-close

**Closed by BryanLa** 2021-06-11 15:43 UTC
Labels: Pri1, assigned-to-author, azure-stack-hub/subsvc, azure-stack/svc, doc-bug, triaged
